# This is a config for E2B sandbox template.
# You can use template ID (27p83vh74s3wirjsvet5) or template name (vibe-nextjs-tanishijanweja-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-tanishijanweja-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-tanishijanweja-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-tanishijanweja-2')

team_id = "b795779d-0747-4ed1-a2cf-129dc5f88dcc"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-tanishijanweja-2"
template_id = "27p83vh74s3wirjsvet5"
